name: testtest
on:
  workflow_dispatch:
    inputs:
      appName:
        description: "Application to Do DB Migration"
        required: true
        type: choice
        options:
          - api
          - customer_dashboard
          - dev_dashboard
      branchName:
        description: "Deploy to which environment"
        required: true
        type: choice
        options:
          - debug
          - develop
          - stage
          - production
env:
  appNameC : ${{ inputs.appName//_/-}}
jobs:
  db_migration:
    uses: ./.github/workflows/run.yml
    with:
      app_name: colorkrew_${{ env.appNameC }}
      aks_namespace: colorkrew-id-${{ env.appNameC }}
      aks_chart_name: ${{ env.appNameC }}-chart
      aks_chart_dir_name: ${{ env.appNameC }}-chart
      aks_chart_template_name: ${{ env.appNameC }}.yaml
      branchName: ${{ inputs.branchName }}
    secrets: inherit
