
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Check release info
      run: |
        echo "${{ steps.get_release.outputs.id }}"
        echo "${{ steps.get_release.outputs.html_url }}"
        echo "${{ steps.get_release.outputs.upload_url }}"
        echo "${{ steps.get_release.outputs.tag_name }}"

