name: testtest
on:
  workflow_dispatch:
    inputs:
      appName:
        description: "Application to Do DB Migration"
        required: true
        options:
          - api
          - customer_dashboard
          - dev_dashboard
      branchName:
        description: "Deploy to which environment"
        required: true
        type: choice
        options:
          - debug
          - develop
          - stage
          - production
jobs:
  db_migration:
    uses: ./.github/workflows/run.yml
    with:
      app_name: colorkrew_${{ inputs.appName }}
      aks_namespace: colorkrew-id-${{ inputs.appName//_/-}}
      aks_chart_name: ${{ inputs.appName//_/-}}-chart
      aks_chart_dir_name: ${{ inputs.appName//_/-}}-chart
      aks_chart_template_name: ${{ inputs.appName//_/-}}.yaml
      branchName: ${{ inputs.branchName }}
    secrets: inherit
