
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "body.md"
        tag: ${{ github.run_id }}
        token: ${{ secrets.GITHUB_TOKEN }}
