
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check release info
      run: |
        echo "prBody=${{ github.event.pull_request.body }}" >> $GITHUB_ENV
        echo "prTitle=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
        echo "prTag=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
