
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check release info!
      run: |
        echo "${{ github.event.pull_request }}"
