name: testtest
on:
  workflow_dispatch:
    inputs:
      appName:
        description: "Application to Do DB Migration"
        required: true
        type: choice
        options:
          - api
          - customer_dashboard
          - dev_dashboard
      branchName:
        description: "Deploy to which environment"
        required: true
        type: choice
        options:
          - debug
          - develop
          - stage
          - production
jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      appNameChanged: ${{ steps.vars.outputs.appNameChanged }}
    steps:
      - name: set values
        id: vars
        run: |
          echo "appNameChanged=${{ outputs.appName }}" | tr _ - >> $GITHUB_OUTPUT
  db_migration:
    uses: ./.github/workflows/run.yml
    with:
      app_name: colorkrew_${{ needs.set-vars.outputs.appNameChanged }}
      aks_namespace: colorkrew-id-${{ needs.set-vars.outputs.appNameChanged }}
      aks_chart_name: ${{ needs.set-vars.outputs.appNameChanged }}-chart
      aks_chart_dir_name: ${{ needs.set-vars.outputs.appNameChanged }}-chart
      aks_chart_template_name: ${{ needs.set-vars.outputs.appNameChanged }}.yaml
      branchName: ${{ inputs.branchName }}
    secrets: inherit
