name:run

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      aks_namespace:
        required: true
        type: string
      aks_chart_name:
        required: true
        type: string
      aks_chart_dir_name:
        required: true
        type: string
      aks_chart_template_name:
        required: true
        type: string
      branchName:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo ${{inputs.app_name}}
          echo ${{inputs.aks_namespace}}
          echo ${{inputs.aks_chart_name}}
          echo ${{inputs.aks_chart_dir_name}}
          echo ${{inputs.aks_chart_template_name}}
          echo ${{inputs.branchName}}
          
